version: '2'

services:

  server:
    build:
      args:
        - CONTAINER_UID=${BX_CONTAINER_UID}
        - CONTAINER_GID=${BX_CONTAINER_GID}
        - CONTAINER_USER=bx
        - CONTAINER_GROUP=bx
    environment:
      - CONTAINER_UID=${BX_CONTAINER_UID}
      - CONTAINER_GID=${BX_CONTAINER_GID}
      - CONTAINER_USER=bx
      - CONTAINER_GROUP=bx