
version: '3.8'

services:

  memcache:
    image: memcached:alpine
    container_name: bx-memcache
    restart: always
    networks:
      bx:
        aliases:
          - memcache

  redis:
    image: redis
    container_name: bx-redis
    restart: always
    networks:
      bx:
        aliases:
          - redis

  push-server-sub:
    image: ikarpovich/bitrix-push-server
    container_name: bx-push-sub
    restart: always
    build:
      context: ./push-server
    environment:
      - REDIS_HOST=redis
      - LISTEN_HOSTNAME=0.0.0.0
      - LISTEN_PORT=${BX_PUSH_SUB_PORT}
      - SECURITY_KEY=${BX_PUSH_SECURITY_KEY}
      - MODE=sub
    ports:
      - ${BX_PUSH_SUB_PORT}:${BX_PUSH_SUB_PORT}
    labels:
      - traefik.port=${BX_PUSH_SUB_PORT}
      - traefik.protocol=http
      - traefik.frontend.rule=Host:${BX_PUSH_SUB_HOST}
    networks:
      bx:
        aliases:
          - ${BX_PUSH_SUB_HOST}

  push-server-pub:
    image: ikarpovich/bitrix-push-server
    container_name: bx-push-pub
    restart: always
    build:
      context: ./push-server
    environment:
      - REDIS_HOST=redis
      - LISTEN_HOSTNAME=0.0.0.0
      - LISTEN_PORT=${BX_PUSH_PUB_PORT}
      - SECURITY_KEY=${BX_PUSH_SECURITY_KEY}
      - MODE=pub
    networks:
      bx:
        aliases:
          - ${BX_PUSH_PUB_HOST}

  mysql:
    build:
      context: ./mysql
      args:
        - BX_MYSQL_IMAGE=${BX_MYSQL_IMAGE}
    container_name: bx-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${BX_MYSQL_ROOT_PASSWORD}
      - BX_MYSQL_IMAGE=${BX_MYSQL_IMAGE}
    ports:
      - ${BX_MYSQL_PORT}:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ${BX_LOGS_PATH}/mysql:/var/log/mysql
    networks:
      bx:
        aliases:
          - mysql
          
  postgres:
    image: postgres
    container_name: bx-postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${BX_MYSQL_ROOT_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      bx:
        aliases:
          - postgres


  php-fpm:
    build:
      context: ./php${BX_PHP_VERSION}
      args:
        - BX_XDEBUG_IP=${BX_XDEBUG_IP}
        - BX_XDEBUG_PORT=${BX_XDEBUG_PORT}
        - BX_DEFAULT_CHARSET=${BX_DEFAULT_CHARSET}
        - CONTAINER_UID=${BX_CONTAINER_UID}
        - CONTAINER_GID=${BX_CONTAINER_GID}
        - CONTAINER_USER=bx
        - CONTAINER_GROUP=bx
        - BX_SMTP_PORT=${BX_SMTP_PORT}
        - BX_SMTP_FROM=${BX_SMTP_FROM}
    container_name: bx-php-fpm
    restart: always
    environment:
      - CONTAINER_UID=${BX_CONTAINER_UID}
      - CONTAINER_GID=${BX_CONTAINER_GID}
      - CONTAINER_USER=bx
      - CONTAINER_GROUP=bx
      - BX_SMTP_PORT=${BX_SMTP_PORT}
      - BX_SMTP_FROM=${BX_SMTP_FROM}
    volumes:
      - ${BX_LOGS_PATH}/php-fpm:/var/log/php-fpm
      - bx-public:/var/www/public_html
      - bx-modules:/media/bitrix/modules
      - bx-langs:/media/bitrix/langs
    extra_hosts:
      - ${BX_UPDATE_HOST}
    networks:
      bx:
        aliases:
          - php-fpm

  nginx:
    build:
      context: ./nginx
      args:
        - CONTAINER_UID=${BX_CONTAINER_UID}
        - CONTAINER_GID=${BX_CONTAINER_GID}
        - CONTAINER_USER=bx
        - CONTAINER_GROUP=bx
    ports:
      - ${BX_HTTP_PORT}:80
      - ${BX_HTTPS_PORT}:443
    container_name: bx-nginx
    restart: always
    environment:
      - BX_DEFAULT_HOST=${BX_DEFAULT_HOST}
      - BX_DEFAULT_LOCAL_DOMAIN=${BX_DEFAULT_LOCAL_DOMAIN}
      - BX_HOST_AUTOCREATE=${BX_HOST_AUTOCREATE}
      - CONTAINER_UID=${BX_CONTAINER_UID}
      - CONTAINER_GID=${BX_CONTAINER_GID}
      - CONTAINER_USER=bx
      - CONTAINER_GROUP=bx
    volumes:
      - ${BX_LOGS_PATH}/nginx:/var/log/nginx
      - bx-public:/var/www/public_html
      - bx-modules:/media/bitrix/modules
    networks:
      bx:
        aliases:
          - nginx
          - bitrix24.localhost
          - bxutf.localhost
          - localhost

  node:
    build:
      context: ./node
    container_name: bx-node
    restart: always
    volumes:
      - bx-public:/var/www/public_html
      - bx-modules:/media/bitrix/modules
    networks:
      bx:
        aliases:
          - node

  fakesmtp:
    image: gessnerfl/fake-smtp-server
    container_name: bx-fakesmtp
    restart: always
    networks:
      bx:
        aliases:
          - fakesmtp
    ports:
      - ${BX_SMTP_WEB_PORT}:5080
      - ${BX_SMTP_REST_PORT}:5081
      - ${BX_SMTP_PORT}:5025

  mailcatcher:
    restart: on-failure
    image: dockage/mailcatcher:0.8.2
    ports:
    - "1080:1080"
    - "1025:1025"
    networks:
      bx:
        aliases:
          - mailcatcher

networks:
  bx:

volumes:
  mysql_data:
  postgres_data:
  bx-modules:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${BX_MODULES_PATH}
  bx-public:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${BX_PUBLIC_HTML_PATH}
  bx-langs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nogaevpn/bitrix_repos/langs
